ToDoListMVC/Models/ErrorViewModel.cs
namespace ToDoListMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoListMVC/Models/ToDoHolder.cs
namespace ToDoListMVC.Models
{
    public class ToDoHolder
    {
        public string? name { get; set; }
        public string[]? tasks { get; set; }
    }
}

ToDoListMVC/Models/ToDoItem.cs
namespace ToDoListMVC.Models
{
    public class ToDoItem
    {
        
        public string? ToDoTask { get; set; }
        public bool IsCompleted { get; set; } = false;

        public ToDoItem()
        {

        }
        public ToDoItem(string toDoTask)
        {
            ToDoTask = toDoTask;
        }
    }
}

ToDoListMVC/Models/ToDoList.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel.DataAnnotations;

namespace ToDoListMVC.Models
{
    [ModelBinder]
    public class ToDoList
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string? Id { get; set; }
        [BsonElement("Name")]
        [Required]
        public string? Name { get; set; }
        [BsonElement("Tasks")]
        public List<ToDoItem> Tasks = new List<ToDoItem>();

    }
}

ToDoListMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoListMVC.Models;

namespace ToDoListMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoListMVC/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;
using ToDoListMVC.CRUD;
using ToDoListMVC.Models;

namespace ToDoListMVC.Controllers
{

    public class ToDoController : Controller
    {
        private readonly ToDoCrud toDoCrud;
        public ToDoController(ToDoCrud toDoCrud)
        {
            this.toDoCrud = toDoCrud;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddList(string jsonList)
        {
            ToDoHolder holder = JsonSerializer.Deserialize<ToDoHolder>(jsonList);
            ToDoList list = new ToDoList();
            list.Name = holder.name;
            foreach (var item in holder.tasks)
            {
                list.Tasks.Add(new ToDoItem(item));
            }

            toDoCrud.Create(list);
            return View("List", toDoCrud.GetLists());
        }
        public IActionResult ViewLists()
        {
            return View("List", toDoCrud.GetLists());
        }

        public IActionResult ViewList(ToDoList list)
        {
            return View("WatchList", toDoCrud.Get(list.Id));
        }

        [HttpPost]
        // Den binder ikke modellen og jeg forstår ikke hvorfor?!?!?
        public IActionResult UpdateList(ToDoList model)
        {

            return View("WatchList", toDoCrud.Get(model.Id));
        } 
        public IActionResult RemoveList(string id)
        {
            toDoCrud.Remove(id);
            return View("List", toDoCrud.GetLists());
        }

    }
}

ToDoListMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<form asp-controller="ToDo" asp-action="Index">
    <button type="submit">
        <p>To Do List</p>
    </button>
</form>
<form asp-controller="ToDo" asp-action="ViewLists">
    <button type="submit">
        <p>View Lists</p>
    </button>
</form>

ToDoListMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoListMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoListMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoListMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoListMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoListMVC/Views/ToDo/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<script src="~/lib/jquery/jquery.js"></script>

<h1>Add things to list</h1>

<table>
    <tr>
        <td>
            Listname
        </td>
        <td>
            <input type="text" name="task" id="nameList" />
        </td>
        <tr/>
        <tr>
        <td>
            Task
        </td>
        <td>
            <input type="text" value="" name="task" id="txtTask" />
        </td>
    </tr>
    <tr>
        <td>
            <input type="button" id="btnSave" value="Save" />
        </td>
    </tr>
</table>
<table class="table-condensed" style="width: 100%" id="tableTasks">
    <thead>
        <tr>
            <th>
                Tasks
            </th>
        </tr>
    </thead>
</table>


<input type="button" value="Save Task" name="SaveData" id="btnSaveData" class="btn btn-primary" />








<script>


        $(document).ready(function(){
            $("#btnSave").click(function(){
                AddTask();
            });

            $("#btnSaveData").click(function(){
            SaveList();
        });
        });

        function SaveList(){
            var table = document.getElementById("tableTasks");
            var listName = $("#nameList").val();
            var newarray = new Array();
            $("#tableTasks tr").each(function(){
                $(this).find("td").each(function(){
                    newarray.push($(this).text())
                })
            })
            var complex = {
                name: listName,
                tasks: newarray
            };

            $.ajax({
            type: "POST",
            url: "ToDo/AddList",
            data: {jsonList: JSON.stringify(complex)}
        })
        }

        function AddTask(){
            var Task = "<tr><td>" + $("#txtTask").val() + "</td></tr>";
            $("#tableTasks").last().append(Task);
            $("#txtTask").val("");
        }

</script>

ToDoListMVC/Views/ToDo/List.cshtml
@model IEnumerable<ToDoList>
<h1>List of To Do Lists</h1>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<table>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Details", "ViewList", new {id = item.Id}) |
                @Html.ActionLink("Remove", "RemoveList", new {id = item.Id})
            </td>
        </tr>
    }
    </tbody>
</table>

ToDoListMVC/Views/ToDo/WatchList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ToDoList

@using (Html.BeginForm("UpdateList", "ToDo"))
{
    <h1>@Html.DisplayFor(m => Model.Name)</h1>
    <table>
        <thead>
            <tr>
                <th>
                    Task
                </th>
                <th>
                    Completed
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.Tasks)
            {
                <tr>
                    <td>

                        @Html.DisplayFor(modelItem => item.ToDoTask)

                    </td>

                    <td>
                        <div class="form-group">
                            @Html.EditorFor(m => item.IsCompleted)
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}